## Урок 7
### Введение в линейную алгебру

In [1]:
import numpy as np
import matplotlib.pyplot as plt

__Задание 1__  
Вектор – это частный случай матрицы `1хN` и `Nх1`. Повторите материал для векторов, уделяя особое внимание умножению `A∙B`.
Вычислите, по возможности не используя программирование: `(5Е)^(-1)`, где `Е` – единичная матрица размера `5х5`.

$$E = \begin{bmatrix}
1 & 0 & 0 & 0 & 0 \\ 
0 & 1 & 0 & 0 & 0 \\
0 & 0 & 1 & 0 & 0 \\
0 & 0 & 0 & 1 & 0 \\
0 & 0 & 0 & 0 & 1 \\
\end{bmatrix}$$  

$$E^{-1} = E$$

In [2]:
e = np.identity(5)
e

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [3]:
e5 = 5 * e
e5

array([[5., 0., 0., 0., 0.],
       [0., 5., 0., 0., 0.],
       [0., 0., 5., 0., 0.],
       [0., 0., 0., 5., 0.],
       [0., 0., 0., 0., 5.]])

In [4]:
e5_inv = np.linalg.inv(e5)
e5_inv

array([[ 0.2,  0. ,  0. ,  0. ,  0. ],
       [ 0. ,  0.2,  0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0.2,  0. ,  0. ],
       [-0. , -0. , -0. ,  0.2, -0. ],
       [ 0. ,  0. ,  0. ,  0. ,  0.2]])

__Задание 2__  
Вычислите определитель:
$$\begin{vmatrix}
1 & 2 & 3 \\ 
4 & 0 & 6 \\
7 & 8 & 9 \\
\end{vmatrix}$$

Determinant of a square matrix:
$$\begin{vmatrix}
a & c \\ 
b & d \\
\end{vmatrix} = ad - bc$$

$$\begin{vmatrix}
a_1 & b_1 & c_1 \\ 
a_2 & b_2 & c_2 \\
a_3 & b_3 & c_3 \\
\end{vmatrix} = a_1 b_2 c_3 + a_3 b_1 c_2 + a_2 b_3 c_1 - a_3 b_2 c_1 - a_1 b_3 c_2 - a_2 b_1 c_3$$

In [5]:
# Determinant by formula
1*0*9 + 7*2*6 + 4*8*3 - 7*0*3 - 1*8*6 - 4*2*9 

60

In [6]:
# Determinant using a built-in function
A = np.array([[1, 2, 3], [4, 0, 6], [7, 8, 9]])
np.linalg.det(A)

59.999999999999986

__Задание 3__  
Вычислите матрицу, обратную данной:
$$\begin{vmatrix}
1 & 2 & 3 \\ 
4 & 0 & 6 \\
7 & 8 & 9 \\
\end{vmatrix}$$

Приведите пример матрицы `4х4`, ранг которой равен `1`.

In [7]:
A = np.array([[1, 2, 3], [4, 0, 6], [7, 8, 9]])
A_inv = np.linalg.inv(A)
A_inv

array([[-0.8       ,  0.1       ,  0.2       ],
       [ 0.1       , -0.2       ,  0.1       ],
       [ 0.53333333,  0.1       , -0.13333333]])

In [8]:
np.linalg.matrix_rank(A, 0.0001)

3

__Задание 4__  
Вычислите скалярное произведение двух векторов:  
`(1, 5)`  и  `(2, 8)`

In [9]:
x1 = 1
y1 = 5
x2 = 2
y2 = 8

x1*x2 + y1*y2

42

__Задание 5__  
Вычислите смешанное произведение трех векторов:
`(1, 5, 0)`, `(2, 8, 7)` и `(7, 1.5, 3)` 

$$(\vec{a} \times \vec{b}) \cdot \vec{c} = \vec{a} \cdot (\vec{b} \times \vec{c}) = 
\begin{vmatrix}
x_1 & y_1 & z_1 \\ 
x_2 & y_2 & z_2 \\
x_3 & y_3 & z_3 \\
\end{vmatrix}$$
where  
$\vec{a} = (x_1, y_1, z_1)$  
$\vec{b} = (x_2, y_2, z_2)$  
$\vec{c} = (x_3, y_3, z_3)$

In [10]:
x1 = 1
y1 = 5
z1 = 0
x2 = 2
y2 = 8
z2 = 7
x3 = 7
y3 = 1.5
z3 = 3



### Системы линейных алгебраических уравнений

__Задание 1__  
Решите линейную систему:
$$\begin{bmatrix}
1 & 2 & 3 \\ 
4 & 0 & 6 \\
7 & 8 & 9 \\
\end{bmatrix} 
\cdot X = 
\begin{bmatrix}
12 \\
2 \\
1 \\
\end{bmatrix} 
$$

In [11]:
A = np.array([[1, 2, 3], [4, 0, 6], [7, 8, 9]])
B = np.array([12, 2, 1])
np.linalg.solve(A, B)

array([-9.2       ,  0.9       ,  6.46666667])

__Задание 2__  
Найдите псевдорешение:  
$x + 2y – z = 1$  
$3x – 4y = 7$  
$8x – 5y + 2z = 12$  
$2x – 5z = 7$  
$11x +4y – 7z = 15$

__Задание 3__  
Сколько решений имеет линейная система:
$$\begin{bmatrix}
1 & 2 & 3 \\ 
4 & 5 & 6 \\
7 & 8 & 9 \\
\end{bmatrix} 
\cdot X = 
\begin{bmatrix}
12 \\
2 \\
1 \\
\end{bmatrix}$$    
Если ноль – то измените вектор правой части так, чтобы система стала совместной, и решите ее. 

In [12]:
# Find determinant by formula
1*5*9 + 7*2*6 + 4*8*3 - 7*5*3 - 1*8*6 - 4*2*9 

0

In [13]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[12, 2, 1]])
C = np.concatenate((A, B.T), axis=1) # augmented matrix

print(C)
A_rank = np.linalg.matrix_rank(A, 0.0001)
C_rank = np.linalg.matrix_rank(C, 0.0001)
A_rank, C_rank

[[ 1  2  3 12]
 [ 4  5  6  2]
 [ 7  8  9  1]]


(2, 3)

__Kronecker-Capelli theorem:__  
A system of linear equations is compatible if and only if the rank of the coefficient matrix `A` is equal to that of the augmented matrix `C` obtained from `A` by adding the column of free terms `B`.

The rank of the original matrix `A` is less than the rank of the extended matrix `C`, hence this system does not have any solutions.

__Задание 4__  
Вычислите LU-разложение матрицы:
$$\begin{bmatrix}
1 & 2 & 3 \\ 
2 & 16 & 21 \\
4 & 28 & 73 \\
\end{bmatrix}$$  
После этого придумайте вектор правых частей и решите полученную линейную систему трех уравнений с данной матрицей.

__Задание 5__  
Найдите нормальное псевдорешение недоопределенной системы:  
$x + 2y – z = 1$  
$8x – 5y + 2z = 12$  
Для этого определите функцию `Q(x,y,z)`, равную норме решения, и найдите ее минимум. 

__Задание 6__  
Найдите одно из псевдорешений вырожденной системы:
$$\begin{bmatrix}
1 & 2 & 3 \\ 
4 & 5 & 6 \\
7 & 8 & 9 \\
\end{bmatrix} 
\cdot X = 
\begin{bmatrix}
2 \\
5 \\
11 \\
\end{bmatrix}$$  
Попробуйте также отыскать и нормальное псевдорешение.